apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: manohar2503/aplibrary-frontend:latest
          imagePullPolicy: Always
          env:
            - name: API_BASE
              value: http://backend.books.svc.cluster.local:8000
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: books
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort